"""Declarative base and common entity mixins.

Every entity gets a UUID primary key and audit timestamps. Defaults are computed in Python so they
work identically on SQLite (local/test) and PostgreSQL (prod) without database-specific SQL.
"""

from __future__ import annotations

from datetime import UTC, datetime
from uuid import UUID, uuid4

from sqlalchemy import DateTime, MetaData, Uuid
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


def _utcnow() -> datetime:
    """Return the current timezone-aware UTC timestamp."""
    return datetime.now(UTC)


# Deterministic constraint names so SQLite batch-mode migrations (which recreate a table to ALTER it)
# can rebuild foreign keys and indexes by name. Without a naming convention, autogenerated foreign keys
# are unnamed and Alembic batch operations fail with "Constraint must have a name".
_NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all CardLens ORM entities."""

    metadata = MetaData(naming_convention=_NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """Adds a UUID primary key generated application-side."""

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)


class TimestampMixin:
    """Adds created/updated audit timestamps maintained application-side."""

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow, onupdate=_utcnow)
