"""add bank accounts and debit cards

Revision ID: 43328502f77f
Revises: cede4c0d0719
Create Date: 2026-06-29 00:45:31.207260
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '43328502f77f'
down_revision: str | None = 'cede4c0d0719'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bank', sa.String(length=40), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('ifsc', sa.String(length=11), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bank_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_accounts'))
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_bank'), ['bank'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('debit_cards',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('card_name', sa.String(length=200), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=True),
    sa.Column('reward_format', sa.String(length=40), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_debit_cards_bank_account_id_bank_accounts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_debit_cards_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debit_cards'))
    )
    with op.batch_alter_table('debit_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debit_cards_bank_account_id'), ['bank_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debit_cards_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debit_cards_user_id'))
        batch_op.drop_index(batch_op.f('ix_debit_cards_bank_account_id'))

    op.drop_table('debit_cards')
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_bank_accounts_bank'))

    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
