"""mail accounts

Revision ID: 825d87de7775
Revises: 43328502f77f
Create Date: 2026-06-29 12:22:00.045949
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '825d87de7775'
down_revision: str | None = '43328502f77f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statements_found', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mail_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_accounts'))
    )
    with op.batch_alter_table('mail_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_accounts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_accounts_user_id'))

    op.drop_table('mail_accounts')
    # ### end Alembic commands ###
