"""mail password hints

Revision ID: 9e554a60deb6
Revises: 825d87de7775
Create Date: 2026-06-29 14:25:59.836801
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9e554a60deb6'
down_revision: str | None = '825d87de7775'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hints_enc', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_accounts', schema=None) as batch_op:
        batch_op.drop_column('password_hints_enc')

    # ### end Alembic commands ###
