"""add card registry entries

Revision ID: a443fbd9e0b0
Revises: bc3a2b14ad20
Create Date: 2026-06-28 22:45:36.769455
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a443fbd9e0b0'
down_revision: str | None = 'bc3a2b14ad20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_registry_entries',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('bank', sa.String(length=40), nullable=False),
    sa.Column('card_name', sa.String(length=200), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_confidence', sa.Float(), nullable=False),
    sa.Column('last_verified_at', sa.Date(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('official_links', sa.JSON(), nullable=False),
    sa.Column('community_links', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_registry_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_registry_entries_bank'), ['bank'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_registry_entries_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_registry_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_registry_entries_key'))
        batch_op.drop_index(batch_op.f('ix_card_registry_entries_bank'))

    op.drop_table('card_registry_entries')
    # ### end Alembic commands ###
