"""initial schema

Revision ID: cede4c0d0719
Revises: 
Create Date: 2026-06-29 00:13:30.983262
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cede4c0d0719'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_registry_entries',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('bank', sa.String(length=40), nullable=False),
    sa.Column('card_name', sa.String(length=200), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_confidence', sa.Float(), nullable=False),
    sa.Column('last_verified_at', sa.Date(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('official_links', sa.JSON(), nullable=False),
    sa.Column('community_links', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_registry_entries'))
    )
    with op.batch_alter_table('card_registry_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_registry_entries_bank'), ['bank'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_registry_entries_key'), ['key'], unique=True)

    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revoked_tokens'))
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('card_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bank', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('last4_primary', sa.String(length=4), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('statement_day', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_card_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_accounts'))
    )
    with op.batch_alter_table('card_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_accounts_bank'), ['bank'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('cards',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('bank', sa.String(length=40), nullable=False),
    sa.Column('card_name', sa.String(length=200), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=True),
    sa.Column('registry_key', sa.String(length=120), nullable=True),
    sa.Column('reward_format', sa.String(length=40), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['card_accounts.id'], name=op.f('fk_cards_account_id_card_accounts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cards_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cards'))
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_bank'), ['bank'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_user_id'), ['user_id'], unique=False)

    op.create_table('statements',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('card_id', sa.Uuid(), nullable=True),
    sa.Column('bank', sa.String(length=40), nullable=False),
    sa.Column('card_name', sa.String(length=200), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('bill_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('total_due', sa.Float(), nullable=True),
    sa.Column('minimum_due', sa.Float(), nullable=True),
    sa.Column('reward_points_credited', sa.Integer(), nullable=True),
    sa.Column('reward_points_redeemed', sa.Integer(), nullable=True),
    sa.Column('reward_points_expired', sa.Integer(), nullable=True),
    sa.Column('reward_points_closing', sa.Integer(), nullable=True),
    sa.Column('cashback_earned', sa.Float(), nullable=True),
    sa.Column('reward_type', sa.String(length=40), nullable=True),
    sa.Column('reward_parse_status', sa.String(length=12), nullable=False),
    sa.Column('reward_confidence', sa.Float(), nullable=False),
    sa.Column('reward_parse_reason', sa.String(length=200), nullable=True),
    sa.Column('manual_review_flag', sa.Boolean(), nullable=False),
    sa.Column('parse_confidence', sa.Float(), nullable=False),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['card_accounts.id'], name=op.f('fk_statements_account_id_card_accounts')),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_statements_card_id_cards')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_statements_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statements'))
    )
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statements_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statements_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statements_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_statements_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statements_user_id'))
        batch_op.drop_index(batch_op.f('ix_statements_due_date'))
        batch_op.drop_index(batch_op.f('ix_statements_card_id'))
        batch_op.drop_index(batch_op.f('ix_statements_account_id'))

    op.drop_table('statements')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_user_id'))
        batch_op.drop_index(batch_op.f('ix_cards_bank'))
        batch_op.drop_index(batch_op.f('ix_cards_account_id'))

    op.drop_table('cards')
    with op.batch_alter_table('card_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_card_accounts_bank'))

    op.drop_table('card_accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))

    op.drop_table('revoked_tokens')
    with op.batch_alter_table('card_registry_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_registry_entries_key'))
        batch_op.drop_index(batch_op.f('ix_card_registry_entries_bank'))

    op.drop_table('card_registry_entries')
    # ### end Alembic commands ###
